Feat:관계를 나타내는 뱃지 컴포넌트
sihyonn/sprint-part2-rollingProject pull request #14
Opened 2024-02-26 11:29 UTC by Dharmaparami

## 📌 주요 사항
- [x] '상대와의 관계' 항목은 지인이 기본값으로 선택되어 있습니다. 친구” | “지인” | “동료” | “가족 중에 하나를 고르셔야 합니다.

## 📷 스크린샷
-ui 구현
<img width="233" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/155143543/d2e507df-4882-4167-98f3-5fc78bf2ccbf">
-전체 코드
<img width="890" alt="image" src="https://github.com/sihyonn/sprint-part2-rollingProject/assets/155143543/5c238a62-c363-4345-985c-487633f6946b">

children 프롭으로 지인, 친구, 동료, 가족을 넘기면 해당 ui에 맞게 변합니다.

## 💬 리뷰 시 요구사항![선택]

## #️⃣ 연관 이슈번호
ex) #2

2024-02-26 12:26 UTC, joonyoungchoi0801 approved these changes
<html>
<body>
<!--StartFragment-->
:white_check_mark:


<!--EndFragment-->
</body>
</html>

2024-02-26 12:29 UTC, sihyonn requested changes
현일님 잘 작성해주셨어요 굳쟙👍🏻
아마도 ESLint 이슈로 propTypes까지 써주신거같네요! 이부분은 내일 미팅때 이야기해봅시댱
나머지는 참고해보시면 좋을 것 같습니다. 수고하셨어욜

2024-02-26 12:29 UTC, sihyonn commented on src/components/common/RelationBadge.jsx
> +};
👏🏻

2024-02-26 12:29 UTC, sihyonn commented on src/components/common/RelationBadge.jsx
> +    color: ${({ children }) => badgeColors[children]?.color || '#fff'};
이 스타일링 부분은 가독성을 위해서 아래와 같이 관련되 스타일들끼리 나란히해주시면 훨씬 좋을 것 같습니다!
앞으로 스탕일링 적용할때도 참고하시면 더 좋겠죠?😊(너비나 패딩, display 등등(선)  -> 폰트관련(후))
``` suggestion
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 1rem;

    width: 2.5rem;
    height: 2rem;
    padding: 0 0.8rem;
    background-color: ${({ children }) =>
      badgeColors[children]?.background || '#fff'};
    color: ${({ children }) => badgeColors[children]?.color || '#fff'};
    border-radius: 0.4rem;

    font-size: 1.4rem;
    line-height: 2rem;
```
아! 그리고 font-family는 설정되어 있어서 빼주시고, letter-spacing도 빼도 될 것 같아요!

2024-02-26 12:29 UTC, sihyonn commented on src/components/common/RelationBadge.jsx
> +import theme from '@styles/theme';
import 하지 않아도 작동이 되도록 설정되어있어요!

2024-02-26 12:35 UTC, Dharmaparami commented on src/components/common/RelationBadge.jsx
> +import theme from '@styles/theme';
theme 안되던데요 흑흑흑

2024-02-26 12:43 UTC, ggjiny approved these changes

2024-02-26 13:08 UTC, sihyonn commented on src/components/common/RelationBadge.jsx
> +import theme from '@styles/theme';
why...?

2024-02-27 05:39 UTC, sihyonn approved these changes

2024-02-27 17:32 UTC, closed without merging